name: easy_call_seniors
description: Easy calling app for elderly users
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.7
  url_launcher: ^6.2.5
  flutter_tts: ^3.8.5
  image_picker: ^1.0.7
  permission_handler: ^11.4.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2